services:
  - type: web
    name: marketplace-api
    env: python
    runtime: python3.11
    plan: free
    
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      rm -f db.sqlite3
      python manage.py makemigrations listings
      python manage.py migrate
      python manage.py collectstatic --noinput
      echo "from django.contrib.auth.models import User; User.objects.filter(username='admin-maximin').exists() or User.objects.create_superuser('admin-maximin', 'admin@example.com', 'Marketplace2024!')" | python manage.py shell
    
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --timeout 120
    
    envVars:
      - key: SECRET_KEY
        generateValue: true
      
      - key: DEBUG
        value: "False"
      
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      
      - key: PYTHON_VERSION
        value: "3.11.0"
      
      - key: CORS_ALLOWED_ORIGINS
        value: "https://marketplacemaximin.netlify.app,http://localhost:5173"
      
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      
      - key: CLOUDINARY_API_KEY
        sync: false
      
      - key: CLOUDINARY_API_SECRET
        sync: false
