# Generated by Django 5.2.4 on 2026-04-30 08:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icône (emoji)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyVisitorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('total_visits', models.IntegerField(default=0, verbose_name='Total visites')),
                ('unique_visitors', models.IntegerField(default=0, verbose_name='Visiteurs uniques')),
                ('authenticated_visitors', models.IntegerField(default=0, verbose_name='Visiteurs authentifiés')),
                ('anonymous_visitors', models.IntegerField(default=0, verbose_name='Visiteurs anonymes')),
                ('total_page_views', models.IntegerField(default=0, verbose_name='Pages vues')),
                ('average_duration', models.DurationField(blank=True, null=True, verbose_name='Durée moyenne')),
                ('countries_data', models.JSONField(blank=True, default=dict, verbose_name='Données par pays')),
                ('top_pages', models.JSONField(blank=True, default=list, verbose_name='Pages populaires')),
                ('browsers_data', models.JSONField(blank=True, default=dict, verbose_name='Navigateurs')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Statistique journalière',
                'verbose_name_plural': 'Statistiques journalières',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (Ar)')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='listings/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('views_count', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.category', verbose_name='Catégorie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Session Stripe')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Paiement Stripe')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Acheteur')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='listings.listing', verbose_name='Annonce')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seller', models.BooleanField(default=False, verbose_name='Est vendeur')),
                ('is_buyer', models.BooleanField(default=True, verbose_name='Est acheteur')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Photo de profil')),
                ('cin_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro CIN')),
                ('cin_issue_date', models.DateField(blank=True, null=True, verbose_name='Date de délivrance CIN')),
                ('cin_issue_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de délivrance CIN')),
                ('cin_photo', models.ImageField(blank=True, null=True, upload_to='cin/', verbose_name='Photo CIN (recto)')),
                ('seller_store_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la boutique')),
                ('seller_description', models.TextField(blank=True, null=True, verbose_name='Description de la boutique')),
                ('seller_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Note du vendeur')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clé de session')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Navigateur')),
                ('device_type', models.CharField(blank=True, max_length=50, null=True, verbose_name="Type d'appareil")),
                ('browser', models.CharField(blank=True, max_length=100, null=True, verbose_name='Navigateur')),
                ('os', models.CharField(blank=True, max_length=100, null=True, verbose_name="Système d'exploitation")),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('country_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Code pays')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Région')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('timezone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fuseau horaire')),
                ('url_visited', models.URLField(max_length=500, verbose_name='URL visitée')),
                ('referer', models.URLField(blank=True, max_length=500, null=True, verbose_name='Référent')),
                ('http_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='Méthode HTTP')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Code statut HTTP')),
                ('visit_time', models.DateTimeField(auto_now_add=True, verbose_name='Heure de visite')),
                ('visit_duration', models.DurationField(blank=True, null=True, verbose_name='Durée de la visite')),
                ('is_authenticated', models.BooleanField(default=False, verbose_name='Est authentifié')),
                ('is_ajax', models.BooleanField(default=False, verbose_name='Requête AJAX')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Visiteur',
                'verbose_name_plural': 'Visiteurs',
                'ordering': ['-visit_time'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_active'], name='listings_li_is_acti_03d721_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category'], name='listings_li_categor_cb899d_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city'], name='listings_li_city_e45c53_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='listings_li_price_d6caaa_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='listings_or_status_42c5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer'], name='listings_or_buyer_i_7f8d92_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='listings_or_created_c0ca48_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['ip_address'], name='listings_vi_ip_addr_b9f1ee_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['visit_time'], name='listings_vi_visit_t_6e0c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['country'], name='listings_vi_country_990e93_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['user'], name='listings_vi_user_id_ca9c64_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['is_authenticated'], name='listings_vi_is_auth_c6baeb_idx'),
        ),
    ]
